### ISSUE TITLE
Release RC9

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#55]
This release will include
- [x] tangobox-archive starting properly
- [x] tangobox-web running and providing mTango REST server -  #23 
- [x] shortcuts to connect to containers consoles

The following shell be done, too:
- [x] `/home/tango-cs/bin/run-tangobox-container-root`  which  will run a container with `--user root`
- [x] RC9 branch shell be created with 
   - [x] added _web_ dockerfile and resources
   - [x] added  `run-tangobox-container-root`
   - [x] added `/home/tango-cs/Desktop/*` to `vm` folder
- [x] New Pogo (9.6.1) - #47 
- [x] New ATK (9.2.9) - #47 
- [x] set password to `tango`
- [x] sample client programs #40 
- [x] updated icons for Pogo and Bensikin - #26 
- [x] export

**Comment by piogor** [comment]
RC9 export in progress...

**Comment by piogor** [comment]
The RC9 is exported and available on onedrive:
https://1drv.ms/u/s!AlUXhMBn4oAfjaN4oP1TCn2JXp52rQ

**Please note** that the password has been changed back to `tango` for export purposes.
